name: Working with Environment

on:
  push:
    branches:
    - main
  workflow_dispatch:
  

permissions: 
  contents: write

jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    environment: DEV

    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [14]
    
    steps:
      - id: STEP1
        name: STEP1
        run: echo 'Hello Worlddd' ${{vars.SERVICE_ADDRESS}} ${{vars.KEY1}}
      - name: STEP2
        if: 1+1 == 2
        run: echo ${{github}} ${{github.workspace}} ${{github.event_name}} ${{github.ref_name}}
      
        
