name: Working with Environment

on:
  push:
    branches:
    - main
  workflow_dispatch:
  

jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    environment: DEV
    
    steps:
      - name: STEP1
        run: echo Hello World
