name: ReUse Workflow Demo

on: 
  push:
    branches: 
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: My Action
        uses: ./.github/workflows/maven1.yml

      
