name: ReUse Workflow Demo

on: [workflow_dispatch]

jobs:
  job1:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Call Another Workflow
        uses: ./.github/workflows/maven.yml@main
