name: ReUse Workflow Demo

on: [workflow_dispatch]

jobs:
  job1:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: My Action
        uses: ./.github/workflows/maven1.yml@main

      
