name: Github Action V2

# Event That Trigger
on:
  push:
    branches:
      - main

# Execute Job
jobs:
  job1:
    runs-on: ubuntu-latest
    
    steps:
      - name: Step 1 Checkout
        run: echo 'hello world, lets checkout'
      
      - name: Step 2 Compile
        run: echo 'lets compile'

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Step1 Job 2
        run: echo 'Step 1 of Job2'
        
      - name: Step2 Job 2
        run: echo 'step2 job2'
    

