name: Testing Scripts

on:
  push:
    branches:
    - main

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: step1
        id: step1
        run: ./test.sh
        shell: bash

