name: Testing Scripts

on:
  push:
    branches:
    - main

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    
    steps:
      - name: Chekcout
        uses: actions/checkout@v2.7.0

      - name: step1
        run: |
            chmod +x ./test.sh
            ./test.sh

