
name: TEST 5

on:
  push:
    branches:
    - main

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    
    steps:
      - id: step1
        name: step1
        run: echo 'output=Hello World' >> $GITHUB_OUTPUT
      - id: step2
        name: step2
        run: echo ${{steps.step1.outputs.output}}

      
