name: Test 4

on:
  push:
    branches:
    - main

env:
  key1: Value1
  key2: Value2
  os: ubuntu-latest
  version: 12

jobs:
  job1:
    name: JOB1
    strategy:
      matrix:
        node_version: ['10', '12']
        os: [ubuntu-latest, ubuntu-22.04]


    runs-on: ${{matrix.os}}
    
    steps:
      - name: 'JOB1STEP1'
        run: |
          echo 'JOB1 STEP1' $key1
          echo 'JOB1 STEP11' $key1 $key2 $os $version
          echo ${{ vars }}
      
      - name: 'Setup Node'
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node_version}}
          

