
name: TEST 5

on:
  push:
    branches:
    - main

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    
    outputs:
      output1: ${{steps.step1.outputs.output1}}
    
    steps:
      - id: step1
        name: step1
        run: echo 'output1=Hello World' >> $GITHUB_OUTPUT
      - id: step2
        name: step2
        run: echo ${{steps.step1.outputs.output1}}

  job2:
    name: job2
    runs-on: ubuntu-latest
    needs: job1
    
    steps:
      - id: step21
        name: step21
        run: echo 'Hello World 21' ${{needs.job1.outputs.output1}} 
      
