name: Testing Scripts

on:
  push:
    branches:
    - main

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    
    steps:
      - name: step1
        id: step1
        run: |
            chmod +x ./test.sh
            ./test.sh
        shell: bash

