name: Start Using Actions V3

on:
  push:
    branches: 
      - main


jobs:
  job1:
    name: JOB_1
    runs-on: ubuntu-latest
    
    steps:
      - name: Step1 Job1
        run: echo "Step 1 Job1"
        
      - name: Check out repository
        uses: actions/checkout@v3
     
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
    
      - name: Setup Node
        uses: actions/setup-node@v3

