name: Upload Artifact V1

on: [workflow_dispatch]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: Step1 Make Folder
        run: mkdir downloads
      - name: Make Files
        run: |
          cd downloads
          echo "Delhi" > 1.html
          echo "Calcutta" > 2.html
          echo "Chennai" > 3.html
      - name: List files
        run: ls -R
      
      - name: Change Directory
        run: cd ..
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: assets-v1
          path: ./downloads
  
    
